name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag fastapi:latest
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker tag fastapi:latest ${{ secrets.DOCKERHUB_USERNAME }}/fastapi:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi:latest

    - name: Start Minikube
      run: |
          minikube start
          kubectl config use-context minikube

    - name: Apply Kubernetes Deployment
      run: kubectl apply -f deployment.yaml

    - name: Verify Deployment
      run: kubectl rollout status deployment/myapp

    - name: Check Application Response
      run: |
          minikube service myapp --url | xargs curl -s
